import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Login from '@/components/Login'

import { auth, db } from "@/firebase";
import RegisterUser from '@/components/RegisterUser';
import { useAuthState } from 'react-firebase-hooks/auth';
import Auth from '@/components/Auth';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [user] = useAuthState(auth);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* {user ? console.log(user) : <Auth />} */}
      <Auth />
    </>
  )
}
